cart/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('cartdetail', views.CartDetail, name='cartdetail'),
    path('add/<int:id>/', views.CartAdd, name='CartAdd'),
    path('delete/<int:id>/', views.CartRemove, name='delete'),
    path('checkout', views.Checkout, name='checkout'),
    path('createorder', views.create_order, name='createorder'),
    path('apply_coupon/', views.apply_coupon, name='apply_coupon'),
    path('removecoupon', views.Removecoupon, name='removecoupon'),
    path('cartaddjs/<int:id>/', views.cartaddjs, name='cartaddjs'),
    path('update_cart_quantity/', views.update_cart_quantity, name='update_cart_quantity'),
    path('thanku/', views.thanku, name='thanku'),
    path('selectaddress', views.selectaddress, name='selectaddress'),
    path('createorders', views.create_orders, name='createorders'),
    path('singproduct/guest_cart_add/<int:id>/', views.guest_cart_add, name='guest_cart_add'),
    path('changecolor/guest_cart_add/<int:id>/', views.guest_cart_add, name='guest_cart_add'),
    path('coin_add', views.coin_add, name='coin_add'),
]

tails/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cust.urls')),
    path('',include('owner.urls')),
    path('',include('cart.urls')),
    path('',include('sending_email_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

owner/models.py
from django.db import models
from django.template.defaultfilters import slugify
class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name

class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory_name = models.CharField(max_length=100)

    def __str__(self):
        return self.subcategory_name

class Product(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class productcolor(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    description = models.TextField()
    stock = models.PositiveIntegerField()
    gender = models.CharField(max_length=255)
    age = models.CharField(max_length=50)
    color = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    slug  = models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.color
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product.name +"-"+self.color)
        return super().save(*args, **kwargs)

class ProductImage(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    color = models.ForeignKey(productcolor, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images')
    
    def __str__(self):
        return self.product.name + ' Image'


class Notifications(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.content

templates/adminlogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Login </title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/adminlogin.css' %}">
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  
  <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.1/jquery.validate.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
        <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
        <div class="container">
            <div class="row">
                <div class="col-md-5 mx-auto">
                <div id="first">
                    <div class="myform form ">
                         <div class="logo mb-3">
                             <div class="col-md-12 text-center">
                                <h1>Login</h1>
                             </div>
                        </div>
                       <form action="adminlogin" method="post" name="login">
                        {% csrf_token %}
                               <div class="form-group">
                                  <label for="exampleInputEmail1">Email address</label>
                                  <input type="email" name="email"  class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
                               </div>
                               <div class="form-group">
                                  <label for="exampleInputEmail1">Password</label>
                                  <input type="password" name="password" id="password"  class="form-control" aria-describedby="emailHelp" placeholder="Enter Password">
                               </div>
                               <div class="form-group">
                                  <p class="text-center">By signing up you accept our <a href="#">Terms Of Use</a></p>
                               </div>
                               <div class="col-md-12 text-center ">
                                  <button type="submit" class=" btn btn-block mybtn btn-primary tx-tfm">Login</button>
                               </div>
                               <div class="col-md-12 ">
                                  <div class="login-or">
                                     <hr class="hr-or">
                                     <span class="span-or">or</span>
                                  </div>
                               </div>
                               {% comment %} <div class="col-md-12 mb-3">
                                  <p class="text-center">
                                     <a href="javascript:void();" class="google btn mybtn"><i class="fa fa-google-plus">
                                     </i> Signup using 
                                     </a>
                                  </p>
                               </div> {% endcomment %}
                               <div class="form-group">
                                  <p class="text-center">Don't have account? <a href="#" id="signup">Sign up here</a></p>
                               </div>
                            </form>
                     
                    </div>
                </div>
                  <div id="second">
                      <div class="myform form ">
                            <div class="logo mb-3">
                               <div class="col-md-12 text-center">
                                  <h1 >Signup</h1>
                               </div>
                            </div>
                            <form action="registration" name="registration" method="post">
                              {% csrf_token %}
                               <div class="form-group">
                                  <label for="exampleInputEmail1">Name</label>
                                  <input type="text"  name="name" class="form-control" id="firstname" aria-describedby="emailHelp" placeholder="Enter Firstname">
                               </div>
                               <div class="form-group">
                                  <label for="exampleInputEmail1">Phone number</label>
                                  <input type="tel"  name="phone" class="form-control" id="lastname" aria-describedby="emailHelp" placeholder="Enter phone number">
                               </div> 
                               <div class="form-group">
                                  <label for="exampleInputEmail1">Email address</label>
                                  <input type="email" name="email"  class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
                               </div>
                               <div class="form-group">
                                  <label for="exampleInputEmail1">Password</label>
                                  <input type="password" name="pass1" id="pass1"  class="form-control" aria-describedby="emailHelp" placeholder="Enter Password">
                               </div>
                               <div class="form-group">
                                 <label for="exampleInputEmail1">Confirm password</label>
                                 <input type="password" name="pass2" id="pass2"  class="form-control" aria-describedby="emailHelp" placeholder="Enter Password">
                              </div>
                               <div class="col-md-12 text-center mb-3">
                                  <button type="submit" class=" btn btn-block mybtn btn-primary tx-tfm">Register</button>
                               </div></form>
                               <div class="col-md-12 ">
                                  <div class="form-group">
                                     <p class="text-center"><a href="#" id="signin">Already have an account?</a></p>
                                  </div>
                               </div>
                                </div>
                            
                         </div>
                </div>
            </div>
          </div>   
             
</body>
<script type="text/javascript" src="{% static 'js/adminlogin.js' %}"></script>
</html>

templates/adminusers.html
{% extends 'adminbase.html' %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/adminusers.css' %}">
<link rel="stylesheet" href="{% static 'css/blockbutton.css' %}">{% endblock  %}
{% block container %}
{% block jshead %}<script type="text/javascript" src="{% static 'js/adminuser.js' %}"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round|Open+Sans">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% comment %} <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script> {% endcomment %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"  crossorigin="anonymous">

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% endblock  %}
<div class="table">
    <div class="table-title">
        <div class="row">
            <div class="col-sm-8"><h2>Employee <b>Details</b></h2></div>
            <div class="col-sm-4">
                <button type="button" class="btn btn-info add-new"><i class="fa fa-plus"></i> Add New</button>
            </div>
        </div>
    </div>
    <table class="table table-bordered col-md-8">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col">Last Login</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for d in data %}
            <tr>
                <td>{{d.name}}</td>
                <td>{{d.email}}</td>
                <td>{{d.phone_number}}</td>
                <td>{{d.is_superuser}}</td>
                <td>
                    <div class="col-sm-5">
                        <button type="button" class="btn btn-sm btn-toggle active" data-toggle="button" aria-pressed="true" autocomplete="off">
                          <div class="handle"></div>
                        </button>
                      </div>
                </td>
            </tr>
            {% endfor %}     
        </tbody>
    </table>
</div>  
  {% endblock  %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Categories{% endblock  %}
{% block staticc %} 
<!-- CSS FILES -->        
{% comment %} <link rel="preconnect" href="https://fonts.googleapis.com">

<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> {% endcomment %}

{% comment %} <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap" rel="stylesheet"> {% endcomment %}
                
<link href="{% static '/css/csst/bootstrap.min.css' %}" rel="stylesheet">

<link href="{% static 'css/csst/bootstrap-icons.css' %}" rel="stylesheet">

<link href="{% static 'css/csst/templatemo-topic-listing.css' %}" rel="stylesheet">
 {% endblock  %}
{% block content %}
<section class="explore-section section-padding" id="section_2">
    <div class="container">
            <div class="col-12 text-center">
                <h2 class="mb-4">Select your favourite</h1>
            </div>

        </div>
    </div>

    <div class="container-fluid">
        <div class="row">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item" role="presentation">
                    
                    <a href=""> <button class="nav-link" id="marketing-tab" >All</button></a>
                </li>
                {% for c in cate %}
               
                <li class="nav-item" role="presentation">
                   <a href="{% url 'subcategory' c_id=c.category.id s_id=c.id %}"> <button class="nav-link" id="marketing-tab" >{{c.subcategory_name}}</button></a>
                </li>
                {% endfor %}
                {% comment %} <li class="nav-item" role="presentation">
                    <button class="nav-link" id="finance-tab" data-bs-toggle="tab" data-bs-target="#finance-tab-pane" type="button" role="tab" aria-controls="finance-tab-pane" aria-selected="false">Fish</button>
                </li>

                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="music-tab" data-bs-toggle="tab" data-bs-target="#music-tab-pane" type="button" role="tab" aria-controls="music-tab-pane" aria-selected="false">Pig</button>
                </li>

                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="education-tab" data-bs-toggle="tab" data-bs-target="#education-tab-pane" type="button" role="tab" aria-controls="education-tab-pane" aria-selected="false">Education</button>
                </li>
                <li class="nav-item" role="presentation">
                    <button class="nav-link" id="education-tab" data-bs-toggle="tab" data-bs-target="#education-tab-pane" type="button" role="tab" aria-controls="education-tab-pane" aria-selected="false">Education</button>
                </li> {% endcomment %}
            </ul>
        </div>
    </div>
{% block one %}
    <div class="container">
        <div class="row">

            <div class="col-12">
                <div class="tab-content" id="myTabContent">
                    <div class="tab-pane fade show active" id="design-tab-pane" role="tabpanel" aria-labelledby="design-tab" tabindex="0">
                        <div class="row">
                            
                            {% for d  in data %}
                            {% if d.productimage_set.first %}
                            <div class="col-lg-3 col-md-4 col-12 mb-2 mb-lg-0">
                                <div class="custom-block bg-white shadow-lg">
                                    
                                    <a href="{% url 'singproduct' id=d.productcolor_set.first.id %}">
                                        <div class="d-flex">
                                            <div>
                                                <h5 class="mb-2">{{d.name}}</h5>

                                                {% comment %} <p class="mb-0">{{d.productcolor_set.first.description}}</p> {% endcomment %}
                                            </div>

                                            <span class="badge bg-design rounded-pill bg-black ms-auto">{{d.productcolor_set.first.stock}}</span>
                                        </div>
                                        {% with image=d.productimage_set.first %}
                                        {% if image %}
                                        <img src="{{ image.image.url }}" class="custom-block-image img-fluid" alt="">
                                        {% endif %}
                                        {% endwith %}
                                    </a>
                                </div>
                            </div>
                            {% endif %}
                            {% endfor %}
                           

                           
    </div>{% endblock  %}
</section>
{% endblock  %}

templates/forgot.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <style>
        body {
    background-position: center;
    background-color: #eee;
    background-repeat: no-repeat;
    background-size: cover;
    color: #505050;
    font-family: "Rubik",Helvetica,Arial,sans-serif;
    font-size: 14px;
    font-weight: normal;
    line-height: 1.5;
    text-transform: none;
    }
    
    .forgot{
    background-color: #fff;
    padding: 12px;
    border: 1px solid #dfdfdf;
    }
    
    .padding-bottom-3x {
    padding-bottom: 72px !important;
    }
    
    .card-footer{
    background-color: #fff;
    }
    
    .btn{ 
    
    font-size: 13px;
    }
    
    .form-control:focus {
    color: #495057;
    background-color: #fff;
    border-color: #76b7e9;
    outline: 0;
    box-shadow: 0 0 0 0px #28a745;
    }</style>
    <div class="container padding-bottom-3x mb-2 mt-5">
        <div class="row justify-content-center">
          <div class="col-lg-8 col-md-10">
            <div class="forgot">
                
                <h2>Forgot your password?</h2>
            <p>Change your password in three easy steps. This will help you to secure your password!</p>
            <ol class="list-unstyled">
              <li><span class="text-primary text-medium">1. </span>Enter your email address below.</li>
              <li><span class="text-primary text-medium">2. </span>Our system will send you a temporary otp</li>
              <li><span class="text-primary text-medium">3. </span>Use the otp to reset your password</li>
            </ol>
    
            </div>	
            {% if messages %}
                  
                        {% for message in messages %}
                            {% if '2' in message.message %}
                                <p class="error" style="color: red;">{{ message.message|cut:"(2)" }}</p>
                            {% else %}
                            {% endif %}
                        {% endfor %}
                  
                {% endif %}
            <form class="card mt-4" method="post" action="">
                {% csrf_token %}
              <div class="card-body">
                <div class="form-group">
                  <label for="email-for-pass">Enter your email address</label>
                  <input class="form-control" type="text" id="email-for-pass" required="" name="email"><small class="form-text text-muted">Enter the email address you used during the registration on Tails and co. Then we'll email a otp to this address.</small>
                </div>
              </div>
              <div class="card-footer">
                <button class="btn btn-success" type="submit">Get New Password</button>
                <button class="btn btn-danger"  type="submit">Back to Login</button>
              </div>
            </form>
          </div>
        </div>
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/gregister.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Register</title>
  </head>
  <body>
    <!-- Section: Design Block -->
    {% block content %}
<section class="background-radial-gradient overflow-hidden">
    <style>
      .background-radial-gradient {
        background-color: hsl(218, 41%, 15%);
        background-image: radial-gradient(650px circle at 0% 0%,
            hsl(218, 41%, 35%) 15%,
            hsl(218, 41%, 30%) 35%,
            hsl(218, 41%, 20%) 75%,
            hsl(218, 41%, 19%) 80%,
            transparent 100%),
          radial-gradient(1250px circle at 100% 100%,
            hsl(218, 41%, 45%) 15%,
            hsl(218, 41%, 30%) 35%,
            hsl(218, 41%, 20%) 75%,
            hsl(218, 41%, 19%) 80%,
            transparent 100%);
      }
  
      #radius-shape-1 {
        height: 220px;
        width: 220px;
        top: -60px;
        left: -130px;
        background: radial-gradient(#44006b, #ad1fff);
        overflow: hidden;
      }
  
      #radius-shape-2 {
        border-radius: 38% 62% 63% 37% / 70% 33% 67% 30%;
        bottom: -60px;
        right: -110px;
        width: 300px;
        height: 300px;
        background: radial-gradient(#44006b, #ad1fff);
        overflow: hidden;
      }
  
      .bg-glass {
        background-color: hsla(0, 0%, 100%, 0.9) !important;
        backdrop-filter: saturate(200%) blur(25px);
      }
    </style>
  
    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
      <div class="row gx-lg-5 align-items-center mb-5">
        <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
          <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
            It's time <br />
            <span style="color: hsl(218, 81%, 75%)">for a pet</span>
          </h1>
          <p class="mb-4 opacity-70" style="color: hsl(218, 81%, 85%)">
            Pets are domesticated animals that are kept primarily for companionship, enjoyment, and as members of the family. They play a significant role in the lives of many people, providing love, comfort, and emotional support.
          </p>
        </div>
  
        <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
          <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
          <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>
          {% endblock %}
          <div class="card bg-glass">
            <div class="card-body px-4 py-5 px-md-5">
              <form method="post" action="">
                {% csrf_token %}
                <!-- 2 column grid layout with text inputs for the first and last names -->
                <div class="row">
                  <div class="col-md-6 mb-4">
                    <div class="form-outline">
                      <input type="text" id="form3Example1" class="form-control" name="name" />
                      <label class="form-label" for="form3Example1">Name</label>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-md-6 mb-4">
                    <div class="form-outline">
                      <input type="text" id="form3Example2" class="form-control" name="phone"/>
                      <label class="form-label" for="form3Example2">Phone Number</label>
                    </div>
                  </div>
                </div>
                <div class="form-outline mb-4">
                  <input type="email" id="form3Example3" class="form-control" name="email"/>
                  <label class="form-label" for="form3Example3">Email address</label>
                </div>
                <div class="row">
                    <div class="col-md-6 mb-4">
                      <div class="form-outline">
                        <input type="password" id="form3Example2" class="form-control" name="pass1" />
                        <label class="form-label" for="form3Example2">Password</label>
                      </div>
                    </div>
                  </div>
                <!-- Password input -->
                <div class="form-outline mb-4">
                  <input type="password" id="form3Example4" class="form-control" name="pass2" />
                  <label class="form-label" for="form3Example4">Confirm Password</label>
                </div>
  
                <!-- Checkbox -->
                <!-- <div class="form-check d-flex justify-content-center mb-4">
                  <input class="form-check-input me-2" type="checkbox" value="" id="form2Example33" checked />
                  <label class="form-check-label" for="form2Example33">
                    Subscribe to our newsletter
                  </label>
                </div> -->
  
                <!-- Submit button -->
                <button type="submit" class="btn btn-primary btn-block mb-4">
                  Sign up
                </button>
  
                <!-- Register buttons -->
                <!-- <div class="text-center">
                  <p>or sign up with:</p>
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-facebook-f"></i>
                  </button>
  
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-google"></i>
                  </button>
  
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-twitter"></i>
                  </button>
  
                  <button type="button" class="btn btn-link btn-floating mx-1">
                    <i class="fab fa-github"></i>
                  </button>
                </div> -->
              </form>
              <a class="small text-muted" href="{% url 'login' %}">already have an account</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Section: Design Block -->

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block section %}  <div class="row text-center pt-3">
    <div class="col-lg-6 m-auto">
        <h1 class="h1">Categories of The Month</h1>
        <p>
            Beyond pets, we also stock a diverse range of pet supplies and accessories to meet all your furry friends' needs.
        </p>
    </div>
</div>
<div class="row">
    <div class="col-12 col-md-4 p-5 mt-3">
        {% with id=1 %}
        <a href="category/{{id}}"><img src="https://i.ibb.co/N78DWvD/petss.jpg" class="rounded-circle img-fluid border"></a>
        <h5 class="text-center mt-3 mb-3">Need Pet</h5>
        <p class="text-center"><a class="btn btn-success" href="category/{{id}}">Go Shop</a></p>
        {% endwith %}
    </div>
    {% with id=3   %}
    <div class="col-12 col-md-4 p-5 mt-3">
        <a href="category/{{id}}"><img src="https://i.ibb.co/TqhTqZC/eatingdog.png" class="rounded-circle img-fluid border"></a>
        <h2 class="h5 text-center mt-3 mb-3">For Them</h2>
        <p class="text-center"><a class="btn btn-success">Go Shop</a></p>
    </div>{% endwith %}
    <div class="col-12 col-md-4 p-5 mt-3">
        {% with id=4 %}
        <a href="category/{{id}}"><img src="https://i.ibb.co/PDnjYyS/dogtoyy.jpg" class="rounded-circle img-fluid border"></a>
        <h2 class="h5 text-center mt-3 mb-3">Accessories</h2>
        <p class="text-center"><a class="btn btn-success" href="category/{{id}}">Go Shop</a></p>
        {% endwith %}
    </div>
</div>



{% endblock  %}
{% block featured %}{% endblock  %}

templates/subcategory.html
{% extends 'base.html' %}
{% block carousel %}{% endblock  %}
{% block section %} <div class="row text-center pt-3">
    <div class="col-lg-6 m-auto">
        <h1 class="h1">Categories </h1>
        <p>
            Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
            deserunt mollit anim id est laborum.
        </p>
    </div>
</div>
<div class="row">
    {% for d  in data %}
    <div class="col-12 col-md-4 p-5 mt-3">
        {% with image=d.productimage_set.first %}
        {% if image %}
        <a href="#"><img src="{{ image.image.url }}" class="rounded-circle img-fluid border" width="400px" height="400px"></a>
        {% endif %}
        {% endwith %}
        <h5 class="text-center mt-3 mb-3">{{d.name}}</h5>
        <p class="text-center"><a class="btn btn-success">Go Shop</a></p>
    </div>{% endfor %}</div>{% endblock  %}