cart/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('cartdetail', views.CartDetail, name='cartdetail'),
    path('add/<int:id>/', views.CartAdd, name='CartAdd'),
    path('delete/<int:id>/', views.CartRemove, name='delete'),
    path('checkout', views.Checkout, name='checkout'),
    path('createorder', views.create_order, name='createorder'),
    path('apply_coupon/', views.apply_coupon, name='apply_coupon'),
    path('removecoupon', views.Removecoupon, name='removecoupon'),
    path('cartaddjs/<int:id>/', views.cartaddjs, name='cartaddjs'),
    path('update_cart_quantity/', views.update_cart_quantity, name='update_cart_quantity'),
    path('thanku/', views.thanku, name='thanku'),
    path('selectaddress', views.selectaddress, name='selectaddress'),
    path('createorders', views.create_orders, name='createorders'),
    path('singproduct/guest_cart_add/<int:id>/', views.guest_cart_add, name='guest_cart_add'),
    path('changecolor/guest_cart_add/<int:id>/', views.guest_cart_add, name='guest_cart_add'),
    path('coin_add', views.coin_add, name='coin_add'),
]

tails/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('cust.urls')),
    path('',include('owner.urls')),
    path('',include('cart.urls')),
    path('',include('sending_email_app.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
from cust.models import CustomUser,Userdetails
from owner.models import Product,productcolor,ProductImage
from django.template.defaultfilters import slugify


class Coupon(models.Model):
    code = models.CharField(max_length=20, unique=True)
    minimumamount=models.IntegerField()
    discount = models.FloatField()
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    active = models.BooleanField(default=True)
    category = models.CharField(max_length=50)
    def __str__(self):
        return self.code
    
    
class Usercoupon(models.Model):
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    coupon=models.ForeignKey(Coupon,on_delete=models.CASCADE)
    
class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    coupon=models.ForeignKey(Coupon, on_delete=models.DO_NOTHING,null=True,blank=True)
    coin_discount = models.IntegerField(default=0)
    def __str__(self):
        return self.user.name


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(productcolor, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def get_total_price(self):
        return self.product.price * self.quantity
        
    def __str__(self):
        return f"{self.product.name} - {self.quantity}"

class Address(models.Model):
    custom_name = models.CharField(max_length=50)
    house_name = models.CharField(max_length=50)
    landmark = models.CharField(max_length=30)
    pincode = models.IntegerField()
    city = models.CharField(max_length=20)
    state = models.CharField(max_length=20)
    def __str__(self):
        return self.custom_name




class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    address = models.ForeignKey(Address,on_delete=models.DO_NOTHING)
    total_price=models.DecimalField(max_digits=10, decimal_places=2)
    razor_pay_order_id=models.CharField(max_length=100,null=True,blank=True)
    razor_pay_payment_id=models.CharField(max_length=100,null=True,blank=True)
    razor_pay_payment_signature=models.CharField(max_length=100,null=True,blank=True)
    slug  = models.CharField(max_length=200,null=True,blank=True)
    payment_method = models.CharField(max_length=20)
    coupon_applied=models.ForeignKey(Coupon,on_delete=models.DO_NOTHING,null=True,blank=True)
    coin_discount = models.IntegerField(default=0)
    order_id = models.PositiveBigIntegerField()
    def __str__(self):
        return f"Order {self.pk} for {self.user.name}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(str(self.user.id) +str(self.created_at))
        return super().save(*args, **kwargs)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(productcolor, on_delete=models.DO_NOTHING)
    quantity = models.PositiveIntegerField(default=0)
    last_update=models.DateTimeField(auto_now=True)
    order_status_choices = [
        ('P', 'Processing'),
        ('S', 'Shipped'),
        ('O', 'Out For Delivery'),
        ('D', 'Delivered'),
        ('C', 'Cancelled'),
        ('R', 'Returning')
    ]
    
    status = models.CharField(max_length=1, choices=order_status_choices, default='P')
    total_itemprice=models.DecimalField(max_digits=10, decimal_places=2)
    order_status_choices = [
        ('P', 'Pending'),
        ('R', 'Recieved'),
    ]
    payment_status = models.CharField(max_length=1, choices=order_status_choices, default='P')
    returnpolicy = models.BooleanField(default=True)
    returnstatus = models.BooleanField(default=False)
    def __str__(self):
        return f"{self.product.name} - {self.quantity}"



class Wishlist(models.Model):
    userr = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(productcolor, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.userr)
    
    
from django.db import models

class GuestUser(models.Model):
    identifier = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.identifier

class Gcart(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    guest_user = models.ForeignKey(GuestUser, on_delete=models.CASCADE)

    def __str__(self):
        return f"Cart created at {self.created_at} for Guest User {self.guest_user}"


class GcartItem(models.Model):
    cart = models.ForeignKey(Gcart, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(productcolor, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)

    def get_total_price(self):
        return self.product.price * self.quantity
        
    def __str__(self):
        return  self.quantity
   
class OrderReturn(models.Model):
    orderitem = models.ForeignKey(OrderItem,on_delete=models.CASCADE)
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    return_status_choices = [
        ('P', 'Pending'),
        ('C', 'Collected'),  
        ('R', 'Recieved'),
    ]
    status = models.CharField(max_length=1, choices=return_status_choices, default='P')
    total_price = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.user)
    
   
class Refund(models.Model):
    orderitem = models.ForeignKey(OrderItem,on_delete=models.CASCADE)
    user= models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    def __str__(self):
        return str(self.user)
    
class Wallet(models.Model):
    coins = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)

    def update_total_coins(self):
        total_coins = self.wallethistory_set.aggregate(models.Sum('coins'))['coins__sum']
        if total_coins is None:
            total_coins = 0
        self.coins = total_coins
        self.save()


class Wallethistory(models.Model):
    wallet = models.ForeignKey(Wallet, on_delete=models.CASCADE)
    coins = models.IntegerField(default=0)
    task = models.TextField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.wallet.user)
    

owner/models.py
from django.db import models
from django.template.defaultfilters import slugify
class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name

class Subcategory(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory_name = models.CharField(max_length=100)

    def __str__(self):
        return self.subcategory_name

class Product(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class productcolor(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    description = models.TextField()
    stock = models.PositiveIntegerField()
    gender = models.CharField(max_length=255)
    age = models.CharField(max_length=50)
    color = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    slug  = models.CharField(max_length=200,null=True,blank=True)

    def __str__(self):
        return self.color
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.product.name +"-"+self.color)
        return super().save(*args, **kwargs)

class ProductImage(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    color = models.ForeignKey(productcolor, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images')
    
    def __str__(self):
        return self.product.name + ' Image'


class Notifications(models.Model):
    content = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.content

templates/user/editadress.html
{% extends 'user/profile.html' %}
{% block contents %}
        <div class="modal-content col-md-6" style="margin: 5%;">
            <form method="post" action="">
                {% csrf_token %}
                <div class="modal-header mt-5" >						
                    <h4 class="modal-title">Edit Address</h4>
           
                </div>
                <div class="modal-body">					
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control" required name="cname" value="{{data.custom_name}}">
                    </div>
                    <div class="form-group">
                        <label>House name</label>
                        <input type="text" class="form-control" required name="hname" value="{{data.house_name}}">
                    </div>
                    <div class="form-group">
                        <label>Land mark</label>
                        <input type="text" class="form-control" required name="landmark" value="{{data.landmark}}">
                    </div>
                    <div class="form-group">
                        <label>Pincode</label>
                        <input type="text" class="form-control" required name="pincode" value="{{data.pincode}}">
                    </div>
                    <div class="form-group">
                        <label>City</label>
                        <input type="text" class="form-control" required name="city" value="{{data.city}}"> 
                    </div>
                    <div class="form-group">
                        <label>State</label>
                        <input type="text" class="form-control" required name="state" value="{{data.state}}">
                    </div>
                                    
                </div>
                <div class="modal-footer">
                    <input type="submit" class="btn btn-success" value="Change">
                </div>
            </form>
        </div>
  
   {% endblock  %}

templates/user/invoice.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <title>invoice</title>
    <style>
        .body{
            margin-top:20px;
            background-color:#eee;
            padding-bottom:100px;
            }
            .tr{
                border-radius: 5px;
            }
           
    </style>
  </head>
  <body>
    
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="invoice-title">
                    <h2>Invoice</h2><h3 class="pull-right"> Order id: {{order.order_id}} </h3>
                </div>
                <hr>
                <div class="row">
                    <div class="col-xs-6">
                        <address>
                        <strong>Billed To:</strong><br>
                            {{order.address.custom_name}}<br>
                            {{order.address.house_name}}<br>
                            {{order.address.landmark}}<br>
                            {{order.address.state}}, {{order.address.pincode}}<br>
                            {{order.user.phone_number}}
                        </address>
                    </div>
                    <div class="col-xs-6 text-right">
                        <address>
                        <strong>Shipped To:</strong><br>
                        {{order.address.custom_name}}<br>
                        {{order.address.house_name}}<br>
                        {{order.address.landmark}}<br>
                        {{order.address.state}}, {{order.address.pincode}}<br>
                        {{order.user.phone_number}}
                        </address>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-6">
                        <address>
                            <strong>Payment Method:</strong><br>
                            {{order.payment_method}}<br>
                            {{order.user.email}}
                        </address>
                    </div>
                    <div class="col-xs-6 text-right">
                        <address>
                            <strong>Order Date:</strong><br>
                            {{order.created_at}} <br><br>
                        </address>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><strong>Order summary</strong></h3>
                    </div>
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table table-condensed">
                                <thead>
                                    <tr class="tr">
                                        <td><strong>Item</strong></td>
                                        <td class="text-center"><strong>Price</strong></td>
                                        <td class="text-center"><strong>Quantity</strong></td>
                                        <td class="text-center"><strong>Status</strong></td>
                                        <td class="text-right"><strong>Totals</strong></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    <!-- foreach ($order->lineItems as $line) or some such thing here -->
                                    {% for item in orderitems %}
                                    <tr>
                                        <td>{{item.product.product.name}}</td>
                                        <td class="text-center">{{item.product.price}}</td>
                                        <td class="text-center">{{item.quantity}}</td>
                                        <td class="text-center">{{item.get_status_display}}</td>
                                        <td class="text-right">{{item.total_itemprice}}</td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <td class="thick-line"></td>
                                        <td class="thick-line"></td>
                                        <td class="thick-line"></td>
                                        <td class="thick-line text-center"><strong>Subtotal</strong></td>
                                        <td class="thick-line text-right">{{total}}</td>
                                    </tr>
                                    <tr>
                                        <td class="no-line"></td>
                                        <td class="no-line"></td>
                                        <td class="thick-line"></td>
                                        <td class="no-line text-center"><strong>Shipping</strong></td>
                                        <td class="no-line text-right">15.00</td>
                                    </tr>
                                    <tr>
                                        <td class="no-line"></td>
                                        <td class="no-line"></td>
                                        <td class="thick-line"></td>
                                        <td class="no-line text-center"><strong>Coupon discount</strong></td>
                                        <td class="no-line text-right">{{order.coupon_applied.discount}},{{order.coupon_applied.code}}</td>
                                    </tr>
                                    <tr>
                                        <td class="no-line"></td>
                                        <td class="no-line"></td>
                                        <td class="thick-line"></td>
                                        <td class="no-line text-center"><strong>Total</strong></td>
                                        <td class="no-line text-right">{{order.total_price}}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>










  
  </body>
</html>

templates/user/notifies.html
{% extends 'user/profile.html' %}
{% load static %}
{% block contents %}


{% endblock %}

templates/user/orderitems.html
{% extends 'user/profile.html' %} {% load static %} {% block contents %}

<style>
  .close:focus {
    outline: none;
  }

  .container.justify-content-center {
    margin-top: 200px;
  }

  .modal-header {
    border: none;
  }

  .modal-footer {
    border: none;
  }

  .btn-danger {
    background: #dd2750;
    border: 1px solid #c43352;
  }

  .btn-light {
    border: 1px solid #e7e7e9;
  }

  .btn:focus {
    box-shadow: none;
  }
</style>

<div class="container-fluid">
  <div class="container">
    <div class="d-flex justify-content-between align-items-center py-3">
      <h2 class="h5 mb-0">
        <a href="#" class="text-muted"></a> Order {{order.order_id}}
      </h2>
    </div>
    <div class="row">
      <div class="col-lg-8">
        <div class="card mb-1">
          <div class="card-body">
            <div class="mb-3 d-flex justify-content-between">
              <div>
                <span class="me-3"></span>
              </div>
              <div class="d-flex">
                <button class="btn btn-link p-0 me-3 d-none d-lg-block btn-icon-text">
                  <i class="bi bi-download"></i>
                  <a href="{% url 'generate_invoice' id=order.id %}"><span class="text">Invoice</span></a>
                </button>
                <div class="dropdown">
                  <button class="btn btn-link p-0 text-muted" type="button" data-bs-toggle="dropdown">
                    <i class="bi bi-three-dots-vertical"></i>
                  </button>
                  <ul class="dropdown-menu dropdown-menu-end">
                    <li>
                      <a class="dropdown-item" href="#"><i class="bi bi-pencil"></i> Edit</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#"><i class="bi bi-printer"></i> Print</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <table class="table table-borderless">
              <tbody>
                {% for item in order_items %}
                <tr>
                  <td>
                    <div class="d-flex mb-2">
                      <a href="{% url 'singproduct' id=item.product.id %}">
                        <div class="flex-shrink-0">
                          <img src="{{item.product.productimage_set.first.image.url}}" alt="" width="35"
                            class="img-fluid" />
                        </div>
                      </a>
                      <div class="flex-lg-grow-1 ms-3">
                        <h6 class="small mb-0">
                          <a href="#" class="text-reset">{{item.product.product.name}}</a>
                        </h6>
                        <span class="small">Color: {{item.product.color}}</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    {% if item.status == 'P' %}
                    <span class="badge badge-info">{{item.get_status_display}}</span>
                    {% elif item.status == 'S' %}
                    <span class="badge badge--" style="background-color: orange">{{item.get_status_display}}</span>
                    {% elif item.status == 'O' %}
                    <span class="badge badge-" style="background-color: yellow">{{item.get_status_display}}</span>
                    {% elif item.status == 'D' %}
                    <span class="badge badge-" style="background-color: green">{{item.get_status_display}}</span>
                    {% else %}
                    <span class="badgebadge badge" style="background-color: red">{{item.get_status_display}}</span>
                    {% endif %}
                  </td>
                  {% if item.status != 'C' and item.status != 'D' %}
                  <td>
                    <span class="badge badge" style="color: rgb(201, 120, 120); cursor: pointer" data-toggle="modal"
                      data-target="#exampleModal">cancel item</span>
                  </td>
                  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <div class="container d-flex pl-0">
                            <img src="{{item.product.productimage_set.first.image.url}}" width="35" class="img-fluid" />
                            <h5 class="modal-title ml-2" id="exampleModalLabel">
                              Cancelling the order?
                            </h5>
                          </div>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <p class="text-muted">
                            Order cancelling forever. Are you sure you want to
                            proceed?
                          </p>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-light" data-dismiss="modal">
                            Close
                          </button>
                          <a href="{% url 'userorder_cancel' id=item.id %}"><button type="button"
                              class="btn btn-danger">
                              Cancel
                            </button></a>
                        </div>
                      </div>
                    </div>
                  </div>

                  {% elif item.status == 'D' %}
                  <td>
                    {% if item.orderpolicy == False %} <span class="badge badge"
                      style="color: rgb(201, 120, 120); cursor: pointer">return policy expired</span> {% else %}
                      {% if item.returnstatus == False %}<a href="{% url 'product_return' id=item.id %}"><span class="badge badge" style="color: rgb(80, 79, 79);">return item</span></a>
                      {% else %}returned{% endif %}
                      {% endif %}
                  </td>
                  {% endif %}
                  <td>{{item.quantity}}</td>
                  <td class="text-end">₹{{item.product.price}}</td>
                </tr>
                {% endfor %}
              </tbody>
              <tfoot>
                <tr>
                  <td colspan="2">Subtotal</td>
                  <td class="text-end">₹{{sub_price}}</td>
                </tr>
                <tr>
                  <td colspan="2">Shipping</td>
                  <td class="text-end">₹15.00</td>
                </tr>
                <tr>
                  <td colspan="2">
                    Discount (Code: {{order.coupon_applied.code}})
                  </td>
                  <td class="text-danger text-end">
                    -₹{{order.coupon_applied.discount}}
                  </td>
                </tr>
                <tr>
                  <td colspan="2">Coin discount</td>
                  <td class="text-end">🪙{{order.coin_discount}}</td>
                </tr>
                <tr class="fw-bold">
                  <td colspan="2">TOTAL</td>
                  <td class="text-end">{{order.total_price}}</td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>
        <!-- Payment -->
        <div class="card mb-4">
          <div class="card-body">
            <div class="row">
              <div class="col-lg-6"></div>
              <div class="col-lg-6"></div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <!-- Customer Notes -->
        {% comment %}
        <div class="card mb-4">
          <div class="card-body">
            <h3 class="h6">Customer Notes</h3>
            <p>
              Sed enim, faucibus litora velit vestibulum habitasse. Cras
              lobortis cum sem aliquet mauris rutrum. Sollicitudin. Morbi, sem
              tellus vestibulum porttitor.
            </p>
          </div>
        </div>
        {% endcomment %}
        <div class="card mb-4">
          <!-- Shipping information -->
          <div class="card-body">
            <h3 class="h6">Payment Method</h3>
            <p>
              <br />
              Total: ₹{{order.total_price}}
              <span class="badge bg-success rounded-pill">{{order.payment_method}}</span>
            </p>
            <hr />
            <h3 class="h6">Address</h3>
            <address>
              <strong>{{address.custom_name}}</strong><br />
              {{address.landmark}}<br />
              {{address.city}}, {{address.pincode}}<br />
              Phone:<abbr> {{order.user.phone_number}}</abbr>
            </address>
            <p style="font-size: 10px">
              return policy only for 7 days from purchase
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %} {% block script %} {% endblock %}

templates/user/orders.html
{% extends 'user/profile.html' %}
{% load static %}
{% block st %}
<link rel="stylesheet" href="{% static '/css/styles.min.css' %}">
  {% endblock  %}

{% block contents %}
<div class="row">
  <div class="col-lg-12 p-5 bg-white rounded shadow-sm mb-5">

    <h3>Orders</h3>
    <div class="table-responsive">
      <table class="table">
      
        <tbody>
          {% for order in orders %} <div style="border-radius: 3px; border-color:black;">
          <tr >
            <th scope="row" class="border-0" >
              <div class="p-2" style="  margin-bottom: 20px;">

                {% for order_item in order.items.all %}
    <img src="{{ order_item.product.productimage_set.first.image.url }}" alt="" width="70" class="img-fluid rounded shadow-sm">
{% endfor %}
                <div class="ml-3 d-inline-block align-middle">
                 
                  <h5 class="mb-0"> <a href="#" class="text-dark d-inline-block align-middle"> {{order.address.custom_name}}</a></h5><span class="text-muted font-weight-normal font-italic d-block">Destination:{{order.address.pincode}}</span>
               
                </div></div>
              
            </th>
            <td class="border-0 align-middle"><strong>₹{{order.total_price}}</strong></td>
            <td class="border-0 align-middle"><strong>Nos:{{order.items.count}}</strong></td>
            <td class="border-0 align-middle"> <a href="{% url 'order_deatails' id=order.id %}"><button type="button" class="btn btn-secondary btn-sm">See ordered items</button></td></a>
        
          </tr></div>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <!-- End -->
  </div>
</div>








{% endblock  %}